name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install wrangler
        run: npm install wrangler
      - name: npx wrangler types
        run: npx wrangler types
      - name: npx tsc --init
        run: npx tsc --init
      - name: Install @cloudflare/workers-types
        run: npm install -D @cloudflare/workers-types
      - name: npm ls
        run: npm ls
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}